kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
    - go get -u -v golang.org/x/lint/golint
    - golint ./...
    - go get -v -t -d ./...
    - go build -v ./...
    - go vet ./...
    - go test -v --tags unit ./...    
     