version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - dupword
    - err113
    - errname
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godox
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - paralleltest
    - recvcheck
    - revive
    - rowserrcheck
    - testableexamples
    - testpackage
    - thelper
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - exhaustruct_v5
    - wsl_v5
    - noinlineerr
    - unqueryvet
    - embeddedstructfieldcheck
    - funcorder
    - gocyclo
    - gosmopolitan
    - goconst
    - gomodguard
  settings:
    gocritic:
      disabled-checks:
        - exitAfterDefer
    gomoddirectives:
      replace-local: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
