linters-settings:
  gocritic:
    disabled-checks:
      - exitAfterDefer
  gosec:
    excludes:
      - G113
  gomoddirectives:
    # Allow local `replace` directives.
    # Default: false
    replace-local: true

linters:
  enable-all: true
  disable:
    - tenv
    - wsl
    - varnamelen
    - wrapcheck
    - testpackage
    - whitespace
    - thelper
    - testableexamples
    - recvcheck
    - paralleltest
    - nonamedreturns
    - nlreturn
    - nilnil
    - nilerr
    - nestif
    - mnd
    - lll
    - ireturn
    - gofumpt
    - godox
    - gochecknoinits
    - gochecknoglobals
    - exhaustruct
    - exhaustive
    - forcetypeassert
    - err113
    - depguard
    - errname
    - funlen
    - cyclop
    - contextcheck
    - gocognit
    - maintidx
    - revive
    - dupl
    - dupword
    - rowserrcheck
    - perfsprint
    