// Code generated by "stringer -type=dbConnectInfoType"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ciDatabaseName-1]
	_ = x[ciHost-2]
	_ = x[ciPort-3]
	_ = x[ciIsConnected-4]
}

const _dbConnectInfoType_name = "ciDatabaseNameciHostciPortciIsConnected"

var _dbConnectInfoType_index = [...]uint8{0, 14, 20, 26, 39}

func (i dbConnectInfoType) String() string {
	i -= 1
	if i < 0 || i >= dbConnectInfoType(len(_dbConnectInfoType_index)-1) {
		return "dbConnectInfoType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _dbConnectInfoType_name[_dbConnectInfoType_index[i]:_dbConnectInfoType_index[i+1]]
}
