// Code generated by "stringer -type=dvp"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[dpvBaseline-0]
	_ = x[dpvClientHandlesStatementSequence-1]
}

const _dvp_name = "dpvBaselinedpvClientHandlesStatementSequence"

var _dvp_index = [...]uint8{0, 11, 44}

func (i dvp) String() string {
	if i >= dvp(len(_dvp_index)-1) {
		return "dvp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _dvp_name[_dvp_index[i]:_dvp_index[i+1]]
}
