// Code generated by "stringer -type=DataType"; DO NOT EDIT

package protocol

import "fmt"

const _DataType_name = "DtUnknownDtTinyintDtSmallintDtIntegerDtBigintDtRealDtDoubleDtDecimalDtTimeDtStringDtBytesDtLob"

var _DataType_index = [...]uint8{0, 9, 18, 28, 37, 45, 51, 59, 68, 74, 82, 89, 94}

func (i DataType) String() string {
	if i >= DataType(len(_DataType_index)-1) {
		return fmt.Sprintf("DataType(%d)", i)
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
